name: NickColor
main: me.b303.nickcolor.NickColor
version: maven-version-number
description: Colorizes nicknames
author: blha303
commands:
    fixnick:
        description: Allows user to fix their nickname color or set a new one
permissions:
    nickcolor.fixnick:
        description: Allow user to use /fixnick
        default: true
    nickcolor.autosetnick:
        description: Set color on name automatically
        default: true
